#pragma once

#define SCREEN_WIDTH 640
#define SCREEN_HEIGHT 360
#define TOTAL_PILLARS 15
#define PILLAR_WIDTH 30
#define PILLAR_HEIGHT 960
#define PILLAR_SPACE 260
#define PILLAR_GAP 140
#define JUMP_VELOCITY 3
#define INITIAL_SPEED 100.0f
