#pragma once

#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 450
#define TOTAL_PILLARS 5
#define PILLAR_WIDTH 30
#define PILLAR_HEIGHT 1000
#define PILLAR_SPACE 200
#define PILLAR_GAP 120
#define JUMP_VELOCITY 3
